services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: billing
      MYSQL_USER: billing_user
      MYSQL_PASSWORD: billing_pass
    volumes:
      - ./billing.sql:/docker-entrypoint-initdb.d/billing.sql
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./Billing-Api
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_USER=billing_user
      - DB_PASSWORD=billing_pass
      - DB_NAME=billing
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./OverStore-master
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql-data:

